### PR TITLE
Update some launchscripts, fix Yolk Heroes

### LINKED ISSUE #567: Port Issue: Carmaggedon resolution fix for screens < 640x480
### Device Type

* [ *] Other device (TrimUI smart pro)

### Firmware

* [ *] Crossmix 1.2.1 (Firmware 1.0.4h6)

#### Description

Carmageddon launches in small window in bottom right as detailed here.
https://github.com/dethrace-labs/dethrace/issues/361

Editing Carmaggedon.sh to add --full-screen and -hires args
`./dethrace --full-screen -hires 2>&1 | tee -a ./log.txt` 

Results in the following.

image

I'll leave it up to you guys if you want to implement or not don't have any other devices to test on to see if the additions breaks things on 640x480 devices.

### LINKED ISSUE #1096: Port Issue: OpenRCT2 Missing game files, see README for more info
### Device Type

* [ ] RG351P/M
* [ ] RG351V
* [ ] RG351MP
* [ ] RG353M/V/P
* [ ] RG503
* [ ] RG552
* [ ] RGB10
* [ ] RGB30
* [ ] RK2023
* [ ] X55
* [x] Other device (R36S)
* [ ] All of the above

### Firmware

* [x] ArkOS
* [ ] ArkOS Wummle
* [ ] AmberELEC
* [ ] JelOS
* [ ] RockNix
* [ ] uOS
* [ ] RetroOZ
* [ ] TheRA

#### Description
After copying the official files to the required directories (RCT2/RCT1) I was prompted with an error: 
Missing game files, see README for more info. Which made no sense since the files we're there.
So dived into the script and Saw the check above had no $GAMEDIR infront of it (https://github.com/PortsMaster/PortMaster-New/blob/09a4c79f9aecd73ac472feac75ff77e90eda8b8a/ports/openrct2/OpenRCT2.sh#L38
). So I changed that line to:
```
if [ ! -f "$GAMEDIR/RCT2/Data/g1.dat" ]; then
```
And after that it worked.

#### Reproduction Steps
* Copy files of RCT1/2 to required directories
* Start game
* Encounter error message
* Adjust OpenRCT2.sh on line 38: `if [ ! -f "$GAMEDIR/RCT2/Data/g1.dat" ]; then`
* Start game
* Enjoy OpenRCT2

### PR DESCRIPTION
**Pull request by JeodC**
Resolves #1096 
Resolves #567 
Fixes Yolk Heroes

### CODE REVIEW

**Review by JanTrueno — APPROVED** [review]

File: ports/carmageddon/Carmageddon.sh [hunk 1]
```diff
@@ -17,19 +13,24 @@ else
...
-$ESUDO chmod 666 $CUR_TTY
-
+# Variables
 GAMEDIR="/$directory/ports/carmageddon"
-cd "$GAMEDIR"
 
+# CD and set permissions
+cd $GAMEDIR
+> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
+$ESUDO chmod +x -R $GAMEDIR/*
```
Comment (Cebion) [inline ports/carmageddon/Carmageddon.sh:25]:
```suggestion
$ESUDO chmod +x $GAMEDIR/dethrace
```

File: ports/openrct2/OpenRCT2.sh [hunk 2]
```diff
@@ -13,70 +13,55 @@ else
...
-export TEXTINPUTNOAUTOCAPITALS="Y"
-export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
-
-export LD_LIBRARY_PATH="$GAMEDIR/libs:$LD_LIBRARY_PATH"
-
-echo "Starting game." > $CUR_TTY
-
+# Run the game
+pm_message "Starting game."
 $GPTOKEYB "openrct2" -c openrct2.gptk textinput &
```
Comment (Cebion) [inline ports/openrct2/OpenRCT2.sh:61]: if you have gptokeyb env exports you don't need this line.
```suggestion
$GPTOKEYB "openrct2" -c openrct2.gptk &
```

File: ports/yolkheroes/port.json [hunk 3]
```diff
@@ -21,7 +21,7 @@
     "image": null,
     "rtr": false,
     "exp": false,
-    "runtime": "frt_3.5.2.squashfs",
+    "runtime": "frt_3.6.squashfs",
```
Comment (Cebion) [inline ports/yolkheroes/port.json:24]: Was this tested? Because the frt 3.6 runtime will cause double inputs.
The Controller is not disbaled on frt 3.6

**Review by Cebion — CHANGES_REQUESTED** [review]

File: ports/yolkheroes/port.json (hunk 3 above)
Comment (JeodC) [reply ports/yolkheroes/port.json:24]: I verified it boots and verified it wouldn't boot with current data on the older runtime. Log output said it needs 3.6.

**Review by Cebion — APPROVED** [review]

**Review by kloptops — APPROVED** [review]
